[workspace]
resolver = "2"
members = [
    "crates/elastic",
    "crates/elastic-adapters",
    "crates/elastic-cli",
    "crates/elastic-downstream",
    "crates/elastic-core",
    "crates/elastic-eir",
    "crates/elastic-kv",
    "crates/elastic-kernel",
    "crates/elastic-macros",
    "crates/elastic-runtime",
]

[workspace.package]
edition = "2021"
rust-version = "1.89"
repository = "https://github.com/Memorithm/ElasticXxx"

[workspace.dependencies]
elastic-core = { version = "0.1.0", path = "crates/elastic-core" }
elastic-eir = { version = "0.1.0", path = "crates/elastic-eir" }
elastic-adapters = { version = "0.1.0", path = "crates/elastic-adapters" }
elastic-macros = { version = "0.1.0", path = "crates/elastic-macros" }
elastic-runtime = { version = "0.1.0", path = "crates/elastic-runtime" }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "2.0" }
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
