[workspace]
resolver = "2"
members = [
    "crates/elastic",
    "crates/elastic-adapters",
    "crates/elastic-downstream",
    "crates/elastic-core",
    "crates/elastic-eir",
    "crates/elastic-kv",
    "crates/elastic-macros",
]

[workspace.package]
edition = "2021"
rust-version = "1.89"
repository = "https://github.com/Memorithm/ElasticXxx"
